### ISSUE TITLE
基金信息（编码：003816）获取失败

### ISSUE THREAD

**Issue by imoyao** [refraction-ray/xalpha#130]
在获取基金`003816`时，信息解析失败导致列表超出范围：
```
>>> import xalpha as xa
>>> xa.__version__
'0.11.4'
>>> xa.get_rt('F003816')
2021-06-16 17:21:41.392 | DEBUG    | xalpha.cons:wrapper:661 - Fetching url: http://fund.eastmoney.com/003816.html . Inside function `get_rt_from_ttjj`
2021-06-16 17:21:41.394 | DEBUG    | urllib3.connectionpool:_new_conn:231 - Starting new HTTP connection (1): fund.eastmoney.com:80
2021-06-16 17:21:41.576 | DEBUG    | urllib3.connectionpool:_make_request:461 - http://fund.eastmoney.com:80 "GET /003816.html HTTP/1.1" 200 22530
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/root/venv/lib/python3.7/site-packages/xalpha/universal.py", line 1780, in get_rt
    return get_rt_from_ttjj(code)
  File "/root/venv/lib/python3.7/site-packages/xalpha/universal.py", line 129, in newfunc
    return f_ttl(ttl_hash, *args, **kwargs)
  File "/root/venv/lib/python3.7/site-packages/xalpha/universal.py", line 121, in time_aware
    return func(*args, **kwargs)
  File "/root/venv/lib/python3.7/site-packages/xalpha/universal.py", line 1629, in get_rt_from_ttjj
    estimate = s.select("span[id=gz_gsz]")[0].text  # after loading
IndexError: list index out of range
```
期望结果：
```
>>> xa.get_rt('F163406')
2021-06-16 17:22:35.241 | DEBUG    | xalpha.cons:wrapper:661 - Fetching url: http://fund.eastmoney.com/163406.html . Inside function `get_rt_from_ttjj`
2021-06-16 17:22:35.244 | DEBUG    | urllib3.connectionpool:_new_conn:231 - Starting new HTTP connection (1): fund.eastmoney.com:80
2021-06-16 17:22:35.409 | DEBUG    | urllib3.connectionpool:_make_request:461 - http://fund.eastmoney.com:80 "GET /163406.html HTTP/1.1" 200 27280
2021-06-16 17:22:35.716 | DEBUG    | xalpha.cons:wrapper:661 - Fetching url: http://fundgz.1234567.com.cn/js/163406.js . Inside function `get_rt_from_ttjj`
2021-06-16 17:22:35.718 | DEBUG    | urllib3.connectionpool:_new_conn:231 - Starting new HTTP connection (1): fundgz.1234567.com.cn:80
2021-06-16 17:22:35.815 | DEBUG    | urllib3.connectionpool:_make_request:461 - http://fundgz.1234567.com.cn:80 "GET /js/163406.js HTTP/1.1" 200 159
{'name': '兴全合润混合', 'time': '2021-06-15', 'current': 2.0987, 'market': 'CN', 'currency': 'CNY', 'current_ext': None, 'status': '限大额  (单日累计购买上限3000元)', 'type': '混合型', 'scale': '269.50亿元（2021-03-31）', 'manager': '谢治宇', 'company': '兴证全球基金', 'estimate': 2.0738, 'estimate_time': '2021-06-16 15:00'}
```

**Comment by imoyao** [comment]
相关讨论：#12

**Comment by refraction-ray** [comment]
这个应该是货币基金不存在估值数据，网页爬虫时没有额外写这个逻辑，应该 839c9700a8b644581b04487384de83cb5f9c86cb 已修复该问题
