### ISSUE TITLE
关于具体示例-基本用法-基金和指数信息的获取与分析中的指数代码

### ISSUE THREAD

**Issue by kuangtu** [refraction-ray/xalpha#14]
首先感谢作者提供如此优秀的工具！
zzhli = xa.indexinfo('1399922') ，指数代码"1399922",这条指数之前中证指数通过深交所渠道转发，代码是399922，2019年1月底不在通过深交所转发，公告：http://www.csindex.com.cn/zh-CN/indices/notices-and-announcements-detail/874
通过示例看到行情最新到2019年1月25日。可以替换为000922。

对于指数方面，通过0、1区分沪深交易所，对于中证指数、标普指数后续是否有区分？
比如：中证创新药产业指数-931152，通过xa.indexinfo方法获取不到。可能是行情源的问题？
谢谢！

**Comment by refraction-ray** [comment]
首先关于示例指数部分，感谢您这么细心指出！

关于其他指数的方面，我得说 indexinfo() 是一个历史遗留，现在用作参考标的的话，我推荐统一用 `xa.vinfo(code)` 就好了，这里的代码 code 的格式和 ``xa.get_daily(code)`` 支持的是一样的。关于支持的标的和代码格式，可以参考这里，https://xalpha.readthedocs.io/en/latest/xalpha.html#xalpha.universal.get_daily。
其中标普官网有的指数是都支持的，中证的指数如果沪深交易所没代码的，暂时没有支持，主要原因是没找到合适的数据源。中证官网的数据源似乎仅支持一年的历史数据，更新还不及时（大概有一天多的延迟）。在写这个回复的时候，我又看了下，似乎有 xhr 请求有日线数据，我还要再确定一下，能不能加上中证全部指数数据。

**Comment by refraction-ray** [comment]
最新的 commit 添加了中证指数数据源, `xa.get_daily("ZZ931152")` 即可，如果是用 info 类的话，`xa.vinfo("ZZ931152")` 即可

**Comment by kuangtu** [comment]
赞。通过xa.get_daily("ZZ931152")可以得到数据。本地通过get_daily落地的ZZ931152.csv文件正常。
中证官网指数详情里面perf.xls文件中保留了最近一个月。展示有最近1个月、1年、3年、5年的。扫了一下xalpha代码，通过链接以json方式获取。
但是通过xa.vinfo("ZZ931152")报错：
WARNING:root:Fails due to 'NoneType' object is not subscriptable, now trying backup data source from sina
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1505, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 208, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 68, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for /: 'str' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1529, in safe_na_op
    return na_op(lvalues, rvalues)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1507, in na_op
    result = masked_arith_op(x, y, op)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1026, in masked_arith_op
    result[mask] = op(xrav[mask], y)
TypeError: unsupported operand type(s) for /: 'str' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/moxuansheng/workspace/python/quant_hc/xalpha/xalpha_fund.py", line 92, in <module>
    get_info()
  File "C:/moxuansheng/workspace/python/quant_hc/xalpha/xalpha_fund.py", line 78, in get_info
    df = xa.vinfo("ZZ931152")
  File "C:\ProgramData\Anaconda3\lib\site-packages\xalpha\universal.py", line 2077, in __init__
    df["netvalue"] = df[col] / df.iloc[0][col]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1583, in wrapper
    result = safe_na_op(lvalues, rvalues)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1533, in safe_na_op
    lambda x: op(x, rvalues))
  File "pandas\_libs\algos.pyx", line 690, in pandas._libs.algos.arrmap
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py", line 1533, in <lambda>
    lambda x: op(x, rvalues))
TypeError: unsupported operand type(s) for /: 'str' and 'float'

Process finished with exit code 1

xvinfo也是调用了get_daily方法，通过df计算。这个地方麻烦你再查看一下。谢谢！

**Comment by refraction-ray** [comment]
我想问题应该是中证官网的 df close 列的格式默认是 str 而不是 float。问题不大，我一会儿会修复下

**Comment by kuangtu** [comment]
好的。我就在ZZ工作 ^_^
看了你的文章<xalpha 设计哲学及其他>，很受启发，赞！
对于其他一些内容我们再交流，期望能够为xalpha“添砖加瓦”

**Comment by refraction-ray** [comment]
哈哈，原来是专业人士，欢迎多交流！

**Comment by refraction-ray** [comment]
fixed via https://github.com/refraction-ray/xalpha/commit/4d204880b50dc869ea4ff9e34efe533aa8ca956b
