### ISSUE TITLE
xa.indexinfo接口无法使用

### ISSUE THREAD

**Issue by xzsajo** [refraction-ray/xalpha#169]
![xalpha](https://user-images.githubusercontent.com/12573520/230059205-3eeecd68-4de0-42cb-8b03-832d6a8aa878.jpg)

Traceback (most recent call last):
  File "D:\PycharmProjects\joinquants\Data\test.py", line 6, in <module>
    zzhli = xa.indexinfo("0000922")
  File "D:\PythonMiniconda\lib\site-packages\xalpha\info.py", line 1211, in __init__
    super().__init__(
  File "D:\PythonMiniconda\lib\site-packages\xalpha\info.py", line 342, in __init__
    self._basic_init()  # update self. name rate and price table
  File "D:\PythonMiniconda\lib\site-packages\xalpha\info.py", line 1220, in _basic_init
    factor = float(my_list[-1][3])
IndexError: list index out of range

**Comment by whistorphi64** [comment]
好像现在这个indexinfo不能用了 ，改成vinfo就好了（至少我是如此）

**Comment by refraction-ray** [comment]
新版本直接 indexinfo 重定向到 vinfo，防止接口失效
