### ISSUE TITLE
导入包xalpha包，numpy报错问题

### ISSUE THREAD

**Issue by 0xSchnappi** [refraction-ray/xalpha#188]
python：3.10.12 64bit
numpy: 2.0.1

报错信息：
/root/develop/QuantitativeTrading/funds/venv/bin/python /root/develop/QuantitativeTrading/funds/GetFundsInfo.py                      ─╯
Traceback (most recent call last):
  File "/root/develop/QuantitativeTrading/funds/GetFundsInfo.py", line 15, in <module>
    import xalpha as xa
  File "/root/develop/QuantitativeTrading/funds/venv/lib/python3.10/site-packages/xalpha/__init__.py", line 5, in <module>
    import xalpha.policy
  File "/root/develop/QuantitativeTrading/funds/venv/lib/python3.10/site-packages/xalpha/policy.py", line 5, in <module>
    import pandas as pd
  File "/root/develop/QuantitativeTrading/funds/venv/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/root/develop/QuantitativeTrading/funds/venv/lib/python3.10/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/root/develop/QuantitativeTrading/funds/venv/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/root/develop/QuantitativeTrading/funds/venv/lib/python3.10/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/root/develop/QuantitativeTrading/funds/venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/root/develop/QuantitativeTrading/funds/venv/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

修复办法：
https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from

```shell

pip3 uninstall numpy 
pip3 install numpy==1.26.4

```

**Comment by refraction-ray** [comment]
最新发布已固定numpy版本小于2

**Comment by xmf0811** [comment]
这个问题以前遇到过，谢谢！
