### ISSUE TITLE
当mysql设置lower_case_table_names=1时，xa.get_daily抛异常

### ISSUE THREAD

**Issue by printff** [refraction-ray/xalpha#38]
mysql5.7,centos,lower_case_table_names=1
py代码在win10上跑。
有人说to_sql的时候，要把表名改成小写key.lower()，不知道有没更好的解决方案。

>>> df=xa.get_daily("LK", prev=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\develop\anaconda3\lib\site-packages\xalpha\universal.py", line 1863, in wrapper
    df0.to_sql(key, con=path, if_exists="replace", index=False)
  File "D:\develop\anaconda3\lib\site-packages\pandas\core\generic.py", line 2663, in to_sql
    method=method,
  File "D:\develop\anaconda3\lib\site-packages\pandas\io\sql.py", line 521, in to_sql
    method=method,
  File "D:\develop\anaconda3\lib\site-packages\pandas\io\sql.py", line 1316, in to_sql
    table.create()
  File "D:\develop\anaconda3\lib\site-packages\pandas\io\sql.py", line 648, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "D:\develop\anaconda3\lib\site-packages\pandas\io\sql.py", line 1363, in drop_table
    self.meta.reflect(only=[table_name], schema=schema)
  File "D:\develop\anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 4261, in reflect
    "in %r%s: (%s)" % (bind.engine, s, ", ".join(missing))
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mysql://xa:***@10.10.10.56/xa?charset=utf8): (LK)

**Comment by refraction-ray** [comment]
可以看下你 ``set_backend`` 的代码是怎样的吗，如果用你现在的 sql engine 直接 ``df.to_sql(name, con)`` 是好的吗？name 可以用大写和小写都试一下。如果确实只是大写会报错，别的没问题，那我可以后续代码怎么调整一下。

**Comment by printff** [comment]
engine = create_engine('mysql://xa:123456@10.10.10.56/xa?charset=utf8', echo=True)
xa.set_backend(backend="sql", path=engine)
df=xa.get_daily("LK", prev=5)  # 如果之前取过数据，表已经创建过来，后面再调用就会抛这个异常，首次建表没问题的。

其实这种问题应该是sqlalchemy去兼容才对的，日志有打印下面这句，说明sqlalchemy会去判断是否需要转换成小写，但实际上还是出错了，搞不懂
2020-07-02 16:21:37,830 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'lower_case_table_names'

下面是详细日志
```
2020-07-02 16:21:37,822 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'sql_mode'
2020-07-02 16:21:37,822 INFO sqlalchemy.engine.base.Engine ()
2020-07-02 16:21:37,830 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'lower_case_table_names'
2020-07-02 16:21:37,830 INFO sqlalchemy.engine.base.Engine ()
2020-07-02 16:21:37,832 INFO sqlalchemy.engine.base.Engine SELECT DATABASE()
2020-07-02 16:21:37,832 INFO sqlalchemy.engine.base.Engine ()
2020-07-02 16:21:37,834 INFO sqlalchemy.engine.base.Engine show collation where `Charset` = 'utf8mb4' and `Collation` = 'utf8mb4_bin'
2020-07-02 16:21:37,834 INFO sqlalchemy.engine.base.Engine ()
2020-07-02 16:21:37,836 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
2020-07-02 16:21:37,836 INFO sqlalchemy.engine.base.Engine ()
2020-07-02 16:21:37,837 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
2020-07-02 16:21:37,837 INFO sqlalchemy.engine.base.Engine ()
2020-07-02 16:21:37,838 INFO sqlalchemy.engine.base.Engine SELECT CAST('test collated returns' AS CHAR CHARACTER SET utf8mb4) COLLATE utf8mb4_bin AS anon_1
2020-07-02 16:21:37,838 INFO sqlalchemy.engine.base.Engine ()
2020-07-02 16:21:37,841 INFO sqlalchemy.engine.base.Engine DESCRIBE `LK`
2020-07-02 16:21:37,841 INFO sqlalchemy.engine.base.Engine ()
2020-07-02 16:21:37,844 INFO sqlalchemy.engine.base.Engine SHOW FULL TABLES FROM `xa`
2020-07-02 16:21:37,844 INFO sqlalchemy.engine.base.Engine ()
Traceback (most recent call last):
  File "d:\doc\src\xa\xa.py", line 16, in <module>
    df=xa.get_daily("LK", prev=5)
  File "D:\develop\anaconda3\lib\site-packages\xalpha\universal.py", line 1797, in wrapper
    df0 = pd.read_sql(key, path)
  File "D:\develop\anaconda3\lib\site-packages\pandas\io\sql.py", line 422, in read_sql
    pandas_sql.meta.reflect(only=[sql])
  File "D:\develop\anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 4261, in reflect
    "in %r%s: (%s)" % (bind.engine, s, ", ".join(missing))
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mysql://xa:***@10.10.10.56/xa?charset=utf8): (LK)
```

**Comment by refraction-ray** [comment]
嗯，那感觉应该就是大小写的问题，我现在能想到的方案，就是 xalpha 缓存逻辑里，如果后端是数据库，统一 key.lower() 一下，暂时没想到有什么代码冲突或者其他bug。还有就是，现在版本也支持手动指定key，你可以试试 ``xa.get_daily("LK", key="lk")`` 是否是好的呢。

**Comment by printff** [comment]
指定key，完全正常，谢谢大佬哈

**Comment by refraction-ray** [comment]
我想到的下一版方案是这样
```python
xa.set_backend(backend="sql", path=engine,  key_func=lambda s:s.lower())
```
这样 get_daily 时就在本来 key 的逻辑之上，再作用一次 ``key=key_func(key)``, 默认不给就什么也不做，感觉这样灵活性比较高。以后标的代码里有什么不支持的特殊字符，也可以用户自己定义 key_func 里先处理掉

**Comment by refraction-ray** [comment]
0.9.4 已支持上述 API，不过该 issue 暂时 open，因为 ioconf 的参数现在太多了， 非常灵活，源代码里没有 set_backend doctstirng 接口，也没有文档详细解释，等文档更新之后再 close
