### ISSUE TITLE
数据缓存报错：xalpha.exceptions.ParserFailure: Unrecognized fund, please check fund code you input

### ISSUE THREAD

**Issue by imoyao** [refraction-ray/xalpha#91]
在进行[数据缓存](https://xalpha.readthedocs.io/en/latest/advance.html#id2)时遇到下面报错
由于代码报错
```python
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data_cache.py", line 10, in <module>
    xa.fundinfo("510018", **io)
  File "/root/fmt/backend/fmt/lib/python3.7/site-packages/xalpha/info.py", line 558, in __init__
    dividend_label=dividend_label,
  File "/root/fmt/backend/fmt/lib/python3.7/site-packages/xalpha/info.py", line 353, in __init__
    self._basic_init()
  File "/root/fmt/backend/fmt/lib/python3.7/site-packages/xalpha/info.py", line 576, in _basic_init
    raise ParserFailure("Unrecognized fund, please check fund code you input.")
xalpha.exceptions.ParserFailure: Unrecognized fund, please check fund code you input.
```
导致pymysql报错如下：
```python
  File "/root/fmt/backend/fmt/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'xa510018' at line 1")
[SQL: xa510018]
(Background on this error at: http://sqlalche.me/e/13/f405)

During handling of the above exception, another exception occurred:

```

## 代码
```
from sqlalchemy import create_engine

import xalpha as xa

engine = create_engine('mysql+pymysql://root:111111@127.0.0.1/xadb?charset=utf8')   # 数据库名称和密码为本人自定义
io = {"save": True, "fetch": True, "form": "sql", "path": engine}
xa.fundinfo("510018", **io)
```
## 版本信息

```bash
(fmt) [root@localhost data]# pip freeze |grep xalpha
xalpha==0.11.2
(fmt) [root@localhost data]# pip freeze |grep SQLAlchemy
Flask-SQLAlchemy==2.4.4
SQLAlchemy==1.3.22
(fmt) [root@localhost data]# python --version
Python 3.7.3
```
找到一个相似错误，ref: #25

**Comment by refraction-ray** [comment]
“xalpha.exceptions.ParserFailure: Unrecognized fund, please check fund code you input” 这个错误的意思应该是对应的基金代码不存在，是否想输入的是 501018 呢？

**Comment by imoyao** [comment]
好的，的确是`501018`，因为我是直接复制的文档说明里面的代码，所以报错了，感谢。😂


> “xalpha.exceptions.ParserFailure: Unrecognized fund, please check fund code you input” 这个错误的意思应该是对应的基金代码不存在，是否想输入的是 501018 呢？
